### ISSUE TITLE
Results of running scripts on the files in Example_data.tar.gz

### ISSUE THREAD

**Issue by susutBu** [Tancata/phylo#1]
Hi, Williams. Thanks for your pipeline  for extracting information from analyses using ALE. When I used your script "branchwise_numbers_of_events.py" to extract the the number of DTLO on each branch of Example_data provided, the result I get was differ from the result in example_outputs.md provided. So, what wrong with me.
The command:
`python2 branchwise_numbers_of_events.py`
The results attached 
For example:
                  Branch	Duplications	Transfers	Losses	Originations	CopyNum
my test      216	16.53	2.23	9.74	0.06	93.08
example_outputs.md 216     201.75  34.15   116.89  0.46    1160.26
The difference is very large.
[DTLO.txt](https://github.com/Tancata/phylo/files/7513237/DTLO.txt)

Looking forward your reply

**Comment by Tancata** [comment]
Hi susutBu,

thanks for raising the issue. You're quite right --- actually, your output is the correct result on the set of 100 sample reconciliations in the Example_data.tar.gz archive (as you might imagine, 1160 gene copies on 100 gene families would be quite a lot for an archaeon :)). I think what has happened is that the example outputs were run on the full dataset from Sheridan et al. (2020), of which just 100 sample recs are included in the example folder. I'll confirm this with Paul and update the example info accordingly.

**Comment by susutBu** [comment]
Thank you for checking!

**Comment by Tancata** [comment]
No worries. One note --- I had a look at your Git profile and, if you are planning to incorporate this script into an ALE pipeline, I would perhaps make the parsing of DTLOs from the uml_rec file a little bit more robust than in my simple implementation. Different versions of ALE differ in the number of fields on those lines (for example, the most recent ALE from sszolo's Github gives origination likelihoods for each branch of the tree as another field, which can help to estimate origination probabilities on a branch directly, rather than the approach based on changes in copy number used previously; if you want to estimate origination probabilities on branches, I would take a look at those).

**Comment by susutBu** [comment]
Thanks for you suggestion, I would take your suggestion into account seriously.

**Comment by Tancata** [comment]
I've added a new archive, "New_Example_data", which contains the output for the 100-reconciliation sample.
